package com.code_exercises
/*
Write a method that returns the sum of all even Fibonacci numbers. Consider all Fibonacci numbers that are less than or equal to n.
Each new element in the Fibonacci sequence is generated by adding the previous two elements.
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 */

def evenFibonacciSum(long num){
      if (num==1){
            return 1
      }
      List<Long> fibonacciSeq = [1L,2L];
      for (i in 1..num){
            if (i>=2){
                  fibonacciSeq << fibonacciSeq[i-2]+fibonacciSeq[i-1]
            }
      }
      def filteredList = fibonacciSeq.stream().filter(x -> (x<=num && x%2==0)).mapToLong(x->x).sum()
      return filteredList

}



assert evenFibonacciSum(50) == 44
